# Generated by Django 2.2 on 2020-12-06 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media")),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("capacity", models.IntegerField()),
                ("projector", models.BooleanField(default=False)),
                ("tv", models.BooleanField(default=False)),
                ("air_conditioning", models.BooleanField(default=False)),
                ("images", models.ManyToManyField(to="page.Image")),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client",
                    models.CharField(
                        help_text="Name and Last name of the client who is making this order",
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
                ("comment", models.TextField()),
                (
                    "rooms",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="page.Room"
                    ),
                ),
            ],
        ),
    ]
