# Generated by Django 2.2 on 2020-12-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="galery"),
        ),
    ]
